name: Sync css and js files from elements to wp-theme-2018
on:
  release:
    types: [created]
    env:
      tag: 1 # ${{ github.event.release.tag_name }}
  workflow_dispatch:  # 👈 manual trigger

jobs:
  sync-to-wp-theme-2018:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key for wp-theme-2018
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ELEMENTS }}" > ~/.ssh/elements
          chmod 600 ~/.ssh/elements
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout elements
        run: |
          git clone -b dist/frontend git@github.com:epfl-si/elements.git elements

      - name: Checkout wp-theme-2018
        run: |
          git clone git@github.com:epfl-si/wp-theme-2018.git theme

      - name: Create new branch in wp-theme-2018
        run: |
          cd theme
          git checkout -b feature/update-from-elements-$tag

      - name: Copy css and js files to wp-theme-2018
        run: |
          rm -rf theme/wp-theme-2018/assets
          mkdir -p theme/wp-theme-2018/assets
          rsync -a --exclude='node_modules' --exclude='.git' --exclude='package.json' --exclude='.nojekyll' --exclude='*.map' elements/ theme/wp-theme-2018/assets/

      - name: Commit and Push to wp-theme-2018
        run: |
          cd theme
          git config user.name "github-actions-elements[bot]"
          git config user.email "github-actions-elements[bot]@users.noreply.github.com"
          git add .
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit, skipping push."
          else
            git commit -m "New element version ${{ github.event.release.tag_name }}"
            git push --set-upstream origin feature/update-from-elements-$tag
          fi
